export let frasesRomanticas = [
    "Eres la luz que ilumina mi vida.",
    "Tus ojos son el reflejo de mi felicidad.",
    "Cada día a tu lado es un regalo del destino.",
    "Eres mi razón de sonreír cada mañana.",
    "Tu amor es el motor que impulsa mi existencia.",
    "Eres el sueño hecho realidad que nunca supe que tenía.",
    "Contigo, cada instante se convierte en un recuerdo inolvidable.",
    "Eres la melodía perfecta que da ritmo a mi corazón.",
    "Tu sonrisa ilumina mi mundo en los días más oscuros.",
    "A tu lado, el tiempo se detiene y solo existe el presente.",
    "Eres mi refugio en medio de la tormenta.",
    "No puedo imaginar mi vida sin ti, eres mi otra mitad.",
    "Cada beso tuyo es el sabor del amor en mis labios.",
    "En tus abrazos encuentro la paz que tanto anhelo.",
    "Eres el sueño que nunca quiero despertar.",
    "Eres el motivo por el que mi corazón late más rápido.",
    "Tu amor es el faro que guía mi camino.",
    "Eres la persona con la que quiero envejecer y compartir todos los momentos.",
    "A tu lado, el mundo es un lugar mágico y lleno de posibilidades.",
    "Tus palabras son el bálsamo que cura todas mis heridas.",
    "Eres el regalo más valioso que la vida me ha dado.",
    "Mi amor por ti es más profundo que el océano y más grande que el universo.",
    "En tus ojos encuentro la belleza más pura y sincera.",
    "A tu lado, cada día es un nuevo comienzo lleno de amor.",
    "Eres el sueño que nunca quiero dejar de soñar.",
    "Tu amor es la fuerza que me impulsa a superar cualquier obstáculo.",
    "Eres la pieza que faltaba en mi rompecabezas de vida.",
    "No importa la distancia, mi amor por ti siempre será eterno.",
    "Eres el sol que ilumina mi existencia y la luna que guía mis sueños.",
    "Contigo, el amor es un poema que nunca deja de rimar.",
    "Eres el latido constante en mi corazón, mi razón de ser.",
    "En tus brazos encuentro el abrigo perfecto para mi alma.",
    "Eres mi confidente, mi cómplice y mi compañero de vida.",
    "Oye,oye,me caes bien 😃👌✌ ",
    "Oye puedes venir a mi lugar",
    "A tu lado, el tiempo se vuelve un suspiro interminable.",
    "Eres la inspiración que da vida a mis versos más hermosos.",
    "Tu amor es el mejor regalo que podría recibir en esta vida.",
    "En tus besos encuentro el paraíso que tanto anhelo.",
    "Eres el sueño que siempre quiero vivir y compartir contigo.",
    "A tu lado, cada día es una aventura llena de amor y complicidad.",
    "Eres la razón por la que mis días están llenos de felicidad.",
    "No hay distancia ni obstáculo que pueda separar nuestro amor.",
    "Eres el sueño del que nunca quiero despertar.",
    "A tu lado, el amor se convierte en una poesía eterna.",
    "En tus abrazos encuentro la calma que tanto anhelo.",
    "Tu voz es la melodía que embriaga mis sentidos.",
    "Eres la estrella que guía mis noches oscuras.",
    "En tus labios encuentro el sabor del paraíso.",
    "Eres el suspiro que escapa de mis labios cuando te miro.",
    "A tu lado, cada instante es una historia de amor inolvidable.",
    "Eres el regalo más preciado que la vida me ha dado.",
    "Tu presencia ilumina mi camino y llena mi corazón de alegría.",
    "Eres el destino al que siempre quiero llegar.",
    "En tus manos encuentro la seguridad y la ternura que tanto anhelo.",
    "Eres la inspiración que alimenta mis sueños más profundos.",
    "A tu lado, el mundo se transforma en un jardín de amor.",
    "Eres la respuesta a todas mis preguntas y el sentido de mi existencia.",
    "En tus ojos encuentro la magia que me envuelve por completo.",
    "Eres el abrigo que me protege de cualquier tempestad.",
    "A tu lado, cada momento es una razón para sonreír.",
    "Eres la promesa de un amor eterno que nunca dejará de latir.",
    "Tu risa es la melodía que alegra mi corazón.",
    "Eres el refugio al que siempre quiero volver.",
    "En tus brazos encuentro la paz que tanto anhelo.",
    "Eres la razón por la que mi mundo está lleno de colores.",
    "A tu lado, cada día es una oportunidad para amar más intensamente.",
    "Eres el sueño que siempre supe que merecía vivir.",
    "En tu mirada encuentro la sinceridad y la pasión que me cautivan.",
    "Eres el horizonte al que siempre quiero dirigirme.",
    "A tu lado, el tiempo se detiene y solo existe nuestro amor.",
    "Eres la melodía que se repite una y otra vez en mi corazón.",
    "En tus palabras encuentro el consuelo y la sabiduría del amor.",
    "Eres el faro que ilumina mi camino en las noches más oscuras.",
    "A tu lado, cada beso es el preludio de una historia de amor sin fin.",
    "Eres el tesoro que encontré en el fondo de mi corazón.",
    "En tu sonrisa encuentro la felicidad que siempre buscaba.",
    "Eres el milagro que dio sentido a mi vida.",
    "A tu lado, el amor se convierte en el latido constante de mi corazón.",
    "Eres el sueño que nunca quiero despertar, la realidad que siempre anhelo.",
    "En tus brazos encuentro la calidez que me reconforta.",
    "Eres el ángel que ilumina mi sendero en las noches más frías.",
    "A tu lado, cada día es una aventura llena de pasión y complicidad."
]